### ISSUE TITLE
Failure to compile

### ISSUE THREAD

**Issue by eogniv** [JakenHerman/vm-detection#1]
Hi there,

Having tried to compile this code, I received the following errors:

main.c<133>: warning C4047: '=': 'FILE *' differs in levels of indirection from 'int'
main.c<139>: error C2057: expected constant expression
main.c<139>: error C2466: cannot allocate an array of constant size 0
main.c<139>: error C2133: 'detection': unknown size

I haven't edited the code in any way, and I am not very up to scratch on C, so I can't figure out how to fix these errors.

Please could you shed some light on the errors?

Kind regards.

**Comment by blacklat** [comment]
this is a crap

**Comment by JakenHerman** [comment]
@eogniv, I apologize you're having issues. This project was a school project from so long ago, I'm not even sure I'd be able to point you in the right direction on how to get your issue resolved at this point.

@blacklat This was a school project I did from 4 years ago. I would suggest you not use this in any serious project, as I'm sure it is "crap". Best of luck to you in figuring out an alternative.

**Comment by blacklat** [comment]
> @eogniv, I apologize you're having issues. This project was a school project from so long ago, I'm not even sure I'd be able to point you in the right direction on how to get your issue resolved at this point.
> 
> @blacklat This was a school project I did from 4 years ago. I would suggest you not use this in any serious project, as I'm sure it is "crap". Best of luck to you in figuring out an alternative.

just reading the code for reference but it's so bad that you can't even use it as a reference
